package frames;


import assets.User;
import estate.Estate;
import estate.Operations;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author A
 */
public class UpdateUser extends javax.swing.JFrame {
    
    private User setUser;
    private Operations set;
    private Estate list;
    
    /**
     * Creates new form UpdateProduct
     */
    public UpdateUser(User setUser, Operations set, Estate list) {
        initComponents();
        this.setUser = setUser;
        this.set = set;
        this.list = list;
        Jname.setText(setUser.firstName);
        Jtel.setText(setUser.tel);
        JlastName.setText(setUser.lastName);
        Jsalary.setText(Integer.toString(setUser.salary));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        error_message = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Jname = new javax.swing.JTextField();
        Label3 = new javax.swing.JLabel();
        JlastName = new javax.swing.JTextField();
        Label4 = new javax.swing.JLabel();
        Jtel = new javax.swing.JTextField();
        Label5 = new javax.swing.JLabel();
        Jsalary = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Urun Guncelle");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        error_message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Label2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label2.setText("İsim");

        Label3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label3.setText("Soyisim");

        Label4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label4.setText("Telefon Numarası");

        Label5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label5.setText("Varlık");

        Jsalary.setActionCommand("<Not Set>");

        saveButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveButton.setText("Kaydet");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Title.setText("KULLANICI BİLGİLERİNİ GÜNCELLE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Jsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jtel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JlastName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jname, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(Title))))
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(Title)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label2)
                        .addGap(18, 18, 18)
                        .addComponent(Label3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label4)
                        .addGap(18, 18, 18)
                        .addComponent(Label5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JlastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try{
            if(Jname.getText().equals("")){
                error_message.setForeground(Color.RED);
                error_message.setText("İsim Bos Birakilamaz!");
            }else if(Jtel.getText().equals("")){
                error_message.setForeground(Color.RED);
                error_message.setText("Telefon Numarası Bos Birakilamaz!");
            }else if(JlastName.getText().equals("")){
                error_message.setForeground(Color.RED);
                error_message.setText("Soyisim Bos Birakilamaz!");
            }else if(Jsalary.getText().equals("")){
                error_message.setForeground(Color.RED);
                error_message.setText("Varlık Bos Birakilamaz!");
            }else if(Integer.parseInt(Jsalary.getText())<0){
                error_message.setForeground(Color.RED);
                error_message.setText("Varlık Negatif olamaz!");
            }else{
                boolean result=set.updateUser(setUser.userName,Jname.getText(),JlastName.getText(),Jtel.getText(),Integer.parseInt(Jsalary.getText()));
                if(result){
                    list.refreshTables();
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Kullanıcı güncellenemedi!");
                }
            }
        }catch(NumberFormatException ex){ 
            Logger.getLogger(UpdateUser.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Lütfen Uygun Değerler Giriniz!");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JlastName;
    private javax.swing.JTextField Jname;
    private javax.swing.JTextField Jsalary;
    private javax.swing.JTextField Jtel;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel error_message;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
