package frames;


import assets.RealEstate;
import estate.Estate;
import estate.Operations;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Muhammed Ali LALE
 */
public class UpdateEstate extends javax.swing.JFrame {
    
    RealEstate setEstate;
    Operations set;
    Estate list;
    
    /**
     * Creates new form UpdateProduct
     */
    public UpdateEstate(RealEstate setEstate, Operations set, Estate list) {
        initComponents();
        this.setEstate = setEstate;
        Jtype.setSelectedIndex(setEstate.type);
        Jprice.setText(Integer.toString(setEstate.price));
        Jaddress.setText(setEstate.address);
        Jarea.setText(Integer.toString(setEstate.area));
        this.set = set;
        this.list = list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        error_message = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Jprice = new javax.swing.JTextField();
        Label5 = new javax.swing.JLabel();
        Jarea = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        Jtype = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jaddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Urun Guncelle");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        error_message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Label2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label2.setText("Tür");

        Label3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label3.setText("Adres");

        Label4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label4.setText("Fiyat");

        Label5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label5.setText("Alan");

        Jarea.setActionCommand("<Not Set>");

        saveButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveButton.setText("Kaydet");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setText("TAŞINMAZ BİLGİLERİNİ GÜNCELLE");

        Jtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daire", "Arazi" }));
        Jtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtypeActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(163, 80));

        Jaddress.setColumns(10);
        Jaddress.setRows(4);
        jScrollPane1.setViewportView(Jaddress);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(error_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Jarea)
                                .addComponent(Jprice)
                                .addComponent(Jtype, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Title)))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label2)
                        .addGap(18, 18, 18)
                        .addComponent(Label4)
                        .addGap(18, 18, 18)
                        .addComponent(Label5)
                        .addGap(18, 18, 18)
                        .addComponent(Label3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton)
                    .addComponent(error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        jScrollPane1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try{
            if(Jprice.getText().equals("")){
                error_message.setForeground(Color.RED);
                error_message.setText("Fiyat Bos Birakilamaz!");
            }else if(Jaddress.getText().equals("")){
                error_message.setForeground(Color.RED);
                error_message.setText("Adres Bos Birakilamaz!");
            }else if(Jarea.getText().equals("")){
                error_message.setForeground(Color.RED);
                error_message.setText("Alan Bos Birakilamaz!");
            }else if(Integer.parseInt(Jarea.getText())<0){
                error_message.setForeground(Color.RED);
                error_message.setText("Alan Negatif olamaz!");
            }//else if(Jtype.getText()!="Daire")
            else{
                boolean result=set.updateEstate(setEstate.estateID,Jtype.getSelectedIndex(),Integer.parseInt(Jprice.getText()),Integer.parseInt(Jarea.getText()),Jaddress.getText());
                if(result){
                    list.refreshTables();
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Taşınmaz güncellenemedi!");
                }
            }
        }catch(NumberFormatException ex){ 
            Logger.getLogger(UpdateEstate.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Lütfen Uygun Değerler Giriniz!");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void JtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtypeActionPerformed

   
    
    
    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Jaddress;
    private javax.swing.JTextField Jarea;
    private javax.swing.JTextField Jprice;
    private javax.swing.JComboBox<String> Jtype;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel error_message;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
